# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- task: FuncToolsInstaller@0
  inputs:
    version: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AW Dev'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Hello World"

      Write-Host $(Build.ArtifactStagingDirectory)

      cd TestFunctionApp
      cd FunctionApp1

      ls

      $functionAppName = "aw-qms-ctus-play919878"

      func azure functionapp fetch-app-settings $functionAppName

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$pwd\TestFunctionApp\FunctionApp1\local.settings.json'
    ArtifactName: 'drop'
    publishLocation: 'Container'

