# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world! - Name of branch $(Build.SourceBranchName)
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/*.csproj'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |      
      Write-Host 'Working Directoy: $(System.DefaultWorkingDirectory)'
      ls $(System.DefaultWorkingDirectory)
      ls $(System.DefaultWorkingDirectory)/TestFunctionApp
      ls $(System.DefaultWorkingDirectory)/TestFunctionApp/FunctionApp1
      ls $(System.DefaultWorkingDirectory)/TestFunctionApp/FunctionApp1/bin
      ls $(System.DefaultWorkingDirectory)TestFunctionApp/FunctionApp1/bin/Debug
      ls $(System.DefaultWorkingDirectory)/TestFunctionApp/FunctionApp1/bin/netcoreapp3.1
      ls $(System.DefaultWorkingDirectory)/TestFunctionApp/FunctionApp1/bin/netcoreapp3.1/bin
