# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- task: FuncToolsInstaller@0
  inputs:
    version: 'latest'

- task: PowerShell@2
  enabled: false
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

      Write-Host $pwd

      cd TestFunctionApp

      ls

      $functionAppName = "aw-qms-ctus-play919878"

      func azure functionapp fetch-app-settings $functionAppName

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AW Dev'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Hello World"

      Write-Host $pwd

      cd TestFunctionApp

      ls

      $functionAppName = "aw-qms-ctus-play919878"

      func azure functionapp fetch-app-settings $functionAppName