# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world! - Name of branch $(Build.SourceBranchName)
  displayName: 'Run a one-line script'

- script: |
    Write-Host Powershell script Name of branch $(Build.SourceBranchName)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
